# Python syntax

In [1]:
print("hello world")

hello world


In [4]:
# assign variable with value
x = 2
x

2

# Function and docstring

In [6]:
def add(x, y):
    """The function is to compute the sum of 2 numbers"""
    return x+y    

In [8]:
add(9,1)

10

# Data types in Python
- integer
- floating point number
- boolean
- complex number
- string

In [9]:
x = 1
y = 3.142
z = True
z1 = 2j
z2 = "String"

<class 'complex'>


In [11]:
x, y, z, z1, z2 = 1, 3.142, True, 2j, "String"
print('{}{}{}{}{}'.format(x,y,z,z1,z2))

13.142True2jString


In [13]:
from IPython.core.interactiveshell import InteractiveShell as IS
IS.ast_node_interactivity = "all"

In [14]:
x
y
z
z1
z2

1

3.142

True

2j

'String'

# Casting (conversion of one data type to another)

In [18]:
x = 1.99
y = "-7.3"

int(x)
float(y)

1

-7.3

# List and Tuple

In [20]:
mylist = ["a", "b", "c"]
mytuple = ("a", "b", "c")

mylist[0]
mytuple[0]

'a'

'a'

In [22]:
mylist[0] = 1
mylist[0]

1

In [23]:
mytuple[0] = 1
mytuple[0]

TypeError: 'tuple' object does not support item assignment

# Numpy functions

In [26]:
import numpy as np

In [27]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [29]:
# for debugging purpose, there are 2 important attributes of numpy array
a.shape

(4,)

## output of array.shape:
- 0D-array --> () (scalar)
- 1D-array --> (4,) (vector)
- 2D-array --> (2, 3) (matrix)
- 3D-array --> (4, 2, 3) (tensor) (images normally have 3 color channels) 


In [30]:
a.dtype

dtype('int64')

In [31]:
type(a)

numpy.ndarray

In [36]:
b = np.array(["a", 1, 2])
b[0]
b[1]
b.dtype

'a'

'1'

dtype('<U21')

In [38]:
a1 = np.array([5, 6, 7, 8])
a_long = np.concatenate((a, a1))
a_long

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
print(f"The shape of the new array is {a_long.shape}")

The shape of the new array is (8,)


# Exercises

1. Try to write a simple custome function to determine whether a given integer is odd or even number

In [46]:
def even_odd(x):
    """This function will determine whether the input integer is even or odd"""
    if isinstance(x, int):
        print("Even" if (x%2==0) else "Odd" )
    else: print("this is not an integer")
    
even_odd(3)
even_odd(4)
even_odd(0.5)

Odd
Even
this is not an integer


2. Write simple code to show that Numpy is more efficient in numerical computation of large arrays of data than equivalent Python List

In [47]:
np_array = np.arange(1000)
py_list = list(range(int(1000)))

%time for _ in range(10): np_array*2

CPU times: user 360 µs, sys: 1.46 ms, total: 1.82 ms
Wall time: 2.35 ms


In [49]:
%time for _ in range(10): py_list*2

CPU times: user 42 µs, sys: 1e+03 ns, total: 43 µs
Wall time: 43.9 µs


3. Run the following code

In [50]:

my_arr = np.arange(10)
print(my_arr)
my_arr[4:7] = 25
print(my_arr)
arr_slice = my_arr[4:7]

# Change the first element of arr_slice to -1
arr_slice[0]= -1

print(arr_slice)
print(my_arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3 25 25 25  7  8  9]
[-1 25 25]
[ 0  1  2  3 -1 25 25  7  8  9]


# 3D array as image

In [51]:
# array of shape (2, 4, 2)
x = np.array([[[0, 6, 1], [5, 2, 4], [0, 2, 4], [5, 2, 4]], 
              [[2, 2, 4], [3, 2, 3], [2, 2, 3], [3, 4, 2]]])
x

array([[[0, 6, 1],
        [5, 2, 4],
        [0, 2, 4],
        [5, 2, 4]],

       [[2, 2, 4],
        [3, 2, 3],
        [2, 2, 3],
        [3, 4, 2]]])

In [52]:
x.shape

(2, 4, 3)

# Setup

In [1]:
import sys
# Python 3.7 is required
assert sys.version_info >= (3,7)

import cv2 as cv
import numpy as np

# For reproducibility,
np.random.seed(99)

# Make sure that optimization is enabled
if not cv.useOptimized():
    cv.setUseOptimized(True)

cv.useOptimized()

True

# Load, display and save the image

In [3]:
# img = cv.imread('lena.jfif')
# cv.imshow('image', img)
# cv.waitKey(5000)
# cv.destroyAllWindows()

: 

In [2]:
img = cv.imread('lena.jfif')
cv.imwrite('lena.png', img)

True

In [3]:
a = cv.resize(img, None, 2.5, 2.5, cv.INTER_LINEAR) 
b = cv.resize(img, None, 2.5, 2.5, cv.INTER_CUBIC) 
# c = cv.resize(img, None, 2.5, 2.5, cv.INTER_NEAREST) 
cv.imshow('imagea', a)
cv.imshow('imageb', b)
# cv.imshow('image', c)
cv.waitKey(0)
cv.destroyAllWindows()
